[tools]
go = "1.26.4"

[tasks.sort]
run = "go run sort/${usage_alg}/main.go"
usage = '''
arg　"<alg>" help="Algorithm name"
'''

[tasks.search-bin]
run = "go run search/binary/main.go"

[tasks.link-list]
run = "go run link-list/${usage_alg}/main.go"
usage = '''
arg "<alg>" help="Algorithm name"
'''

[tasks.hash-table]
run = "go run hash-table/hash-table/main.go"

[tasks.stack]
run = "go run stack-queue/stack/main.go"

[tasks.queue]
run = "go run stack-queue/queue/main.go"

[tasks.bt]
run = "go run tree/binary-search/main.go"

[tasks.heap]
run = "go run tree/heap/main.go"
